# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\ML_PROJECTS\mlproject_2\src\UI\add_2_numbers.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(329, 147)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_first_number = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_first_number.setGeometry(QtCore.QRect(200, 10, 113, 20))
        self.txt_first_number.setObjectName("txt_first_number")
        self.txt_second_number = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_second_number.setGeometry(QtCore.QRect(200, 40, 113, 20))
        self.txt_second_number.setObjectName("txt_second_number")
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(156, 79, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_result.setFont(font)
        self.lbl_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_result.setObjectName("lbl_result")
        self.bt_valid = QtWidgets.QPushButton(self.centralwidget)
        self.bt_valid.setGeometry(QtCore.QRect(30, 80, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_valid.setFont(font)
        self.bt_valid.setObjectName("bt_valid")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 329, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ML add two numbers"))
        self.label.setText(_translate("MainWindow", "Enter the fisrt number"))
        self.label_2.setText(_translate("MainWindow", "Enter the second number"))
        self.lbl_result.setText(_translate("MainWindow", "Result"))
        self.bt_valid.setText(_translate("MainWindow", "Calculate"))
